// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLYfIC8D7J_9NdtpRTShHSmLlsuWH1WyQ',
    appId: '1:316453711847:web:7ec3a18cf283f0d7a6d742',
    messagingSenderId: '316453711847',
    projectId: 'flutter--analytics-test',
    authDomain: 'flutter--analytics-test.firebaseapp.com',
    storageBucket: 'flutter--analytics-test.appspot.com',
    measurementId: 'G-62CB1XX7SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2wnYtS8Um8W7sYZpsPDbm5INmJKbSsO4',
    appId: '1:316453711847:android:daea7094117dfab9a6d742',
    messagingSenderId: '316453711847',
    projectId: 'flutter--analytics-test',
    storageBucket: 'flutter--analytics-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiQwNYcJKhzKlFT-4L1LbaRq3Xf8hhLXA',
    appId: '1:316453711847:ios:f27bcf043308a984a6d742',
    messagingSenderId: '316453711847',
    projectId: 'flutter--analytics-test',
    storageBucket: 'flutter--analytics-test.appspot.com',
    iosClientId: '316453711847-fjqnebohdmgppbcquucp09ois8nk80r3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGoogleAnalyticsExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiQwNYcJKhzKlFT-4L1LbaRq3Xf8hhLXA',
    appId: '1:316453711847:ios:af6a8e6beb82764da6d742',
    messagingSenderId: '316453711847',
    projectId: 'flutter--analytics-test',
    storageBucket: 'flutter--analytics-test.appspot.com',
    iosClientId: '316453711847-i1qa1ej73jerc1fl9na84s958veikub6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGoogleAnalyticsExample.RunnerTests',
  );
}
